apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ include "amplication.app.name" . }}-default"
  namespace: {{ .Release.Namespace }}
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ include "amplication.app.name" . }}-default"
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "{{ include "amplication.app.name" . }}-default"
