## Example Values for Minimal

cluster:
  instances: 3
  pods:
    persistentVolume:
      size: 25Gi
  sgInstanceProfile: size-m

defaultStorageClass: ebs
cloudStorage:
  s3:
    enabled: true
    bucket: my-bucket
    path: /stackgres
    region: us-east-1
    accessKeyId: ""
    secretAccessKey: "" 

initScripts:
  enabled: true
  customScripts:
  -  name: my-custom-script
     enabled: true
     data: |
      create database "harbor";