# Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keydb.fullname" . }}-headless
  labels:
    {{- include "keydb.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: {{ .Values.portName | quote }}
    port: {{ .Values.port | int }}
    protocol: TCP
    targetPort: keydb
    {{- if .Values.service.appProtocol.enabled }}
    appProtocol: redis
    {{- end }}
  {{- if .Values.haproxy.enabled }}
  - name: haproxy
    port: {{ .Values.haproxy.port | int }}
    protocol: TCP
    targetPort: haproxy
    {{- if .Values.service.appProtocol.enabled }}
    appProtocol: redis
    {{- end }}
  {{- if .Values.haproxy.stats.enabled }}
  - name: haproxy-stats
    port: {{ .Values.haproxy.stats.port | int }}
    protocol: TCP
    targetPort: stats
    {{- if .Values.service.appProtocol.enabled }}
    appProtocol: http
    {{- end }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "keydb.selectorLabels" . | nindent 4 }}
