{{ if and .Values.cloudStorage.s3.accessKeyId .Values.cloudStorage.s3.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade,post-install,post-upgrade"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  accessKeyId: {{ .Values.cloudStorage.s3.accessKeyId }}
  secretAccessKey: {{ .Values.cloudStorage.s3.secretAccessKey }}
{{ end }}
