{{ if and .Values.configurations.create .Values.configurations.backupconfig.create }}
apiVersion: stackgres.io/v1
kind: SGBackupConfig
metadata:
  name: {{ .Release.Namespace }}-{{ .Release.Name }}-{{ .Values.cluster.configurations.sgBackupConfig }}
  {{- if and .Release.IsInstall .Values.cluster.create }}
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade"
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
  {{- end }}
spec:
  baseBackups:
    retention: {{ .Values.configurations.backupconfig.baseBackups.retention }}
    cronSchedule: "{{ .Values.configurations.backupconfig.baseBackups.cronSchedule }}"
    compression: "{{ .Values.configurations.backupconfig.baseBackups.compression }}"
    performance:
      {{- if .Values.configurations.backupconfig.baseBackups.performance.maxNetworkBandwitdh }}
      maxNetworkBandwitdh: {{ .Values.configurations.backupconfig.baseBackups.performance.maxNetworkBandwitdh }}
      {{- end }}
      {{- if .Values.configurations.backupconfig.baseBackups.performance.maxDiskBandwitdh }}
      maxDiskBandwitdh: {{ .Values.configurations.backupconfig.baseBackups.performance.maxDiskBandwitdh }}
      {{- end }}
      uploadDiskConcurrency: {{ .Values.configurations.backupconfig.baseBackups.performance.uploadDiskConcurrency }}
  storage:
    {{- if not (or .Values.cloudStorage.s3.enabled .Values.cloudStorage.s3Compatible .Values.cloudStorage.gcs .Values.cloudStorage.azureBlob) }}
    type: s3Compatible
    s3Compatible:
      bucket: stackgres
      endpoint: http://{{ .Release.Name }}-minio:9000
      enablePathStyleAddressing: true
      region: k8s
      awsCredentials:
        secretKeySelectors:
          accessKeyId:
            name: {{ .Release.Name }}-minio
            key: accesskey
          secretAccessKey:
            name: {{ .Release.Name }}-minio
            key: secretkey
    {{- end }}
    {{- if .Values.cloudStorage.s3.enabled }}
    type: s3
    s3:
      bucket: "{{ .Values.cloudStorage.s3.bucket }}"
      {{- if .Values.cloudStorage.s3.path }}
      {{ if .Values.cloudStorage.s3.autoAppend }}
      path:  "{{ .Values.cloudStorage.s3.path }}-{{ .Release.Namespace }}-{{ .Release.Name }}"
      {{- else }}
      path: "{{ .Values.cloudStorage.s3.path }}"
      {{- end }}
      awsCredentials:
        secretKeySelectors:
          accessKeyId:
            {{- if .Values.cloudStorage.s3.existingSecret }}
            name: {{ .Values.cloudStorage.s3.existingSecret }}
            key: accessKeyId
            {{- end }}
            {{- if .Values.cloudStorage.s3.accessKeyId }}
            name: {{ .Release.Name }}-aws
            key: accessKeyId
            {{- else }}
            name: "{{ .Values.cloudStorage.s3.awsCredentials.secretKeySelectors.accessKeyId.name }}"
            key: "{{ .Values.cloudStorage.s3.awsCredentials.secretKeySelectors.accessKeyId.key }}"
            {{- end }}
          secretAccessKey:
            {{- if .Values.cloudStorage.s3.existingSecret }}
            name: {{ .Values.cloudStorage.s3.existingSecret }}
            key: secretAccessKey
            {{- end }}
            {{- if .Values.cloudStorage.s3.secretAccessKey }}
            name: {{ .Release.Name }}-aws
            key: secretAccessKey
            {{- else }}
            name: "{{ .Values.cloudStorage.s3.awsCredentials.secretKeySelectors.secretAccessKey.name }}"
            key: "{{ .Values.cloudStorage.s3.awsCredentials.secretKeySelectors.secretAccessKey.key }}"
            {{- end }}
      {{- if .Values.cloudStorage.s3.region }}
      region: "{{ .Values.cloudStorage.s3.region }}"
      {{- end }}
      {{- if .Values.cloudStorage.s3.storageClass }}
      storageClass: "{{ .Values.cloudStorage.s3.storageClass }}"
      {{- end }}
    {{- end }}
    {{- if .Values.cloudStorage.s3Compatible }}
    type: s3Compatible
    s3Compatible:
      bucket: "{{ .Values.cloudStorage.s3Compatible.bucket }}"
      {{- if .Values.cloudStorage.s3Compatible.path }}
      path: "{{ .Values.cloudStorage.s3Compatible.path }}"
      {{- end }}
      awsCredentials:
        secretKeySelectors:
          accessKeyId:
            name: "{{ .Values.cloudStorage.s3Compatible.awsCredentials.secretKeySelectors.accessKeyId.name }}"
            key: "{{ .Values.cloudStorage.s3Compatible.awsCredentials.secretKeySelectors.accessKeyId.key }}"
          secretAccessKey:
            name: "{{ .Values.cloudStorage.s3Compatible.awsCredentials.secretKeySelectors.secretAccessKey.name }}"
            key: "{{ .Values.cloudStorage.s3Compatible.awsCredentials.secretKeySelectors.secretAccessKey.key }}"
      {{- if .Values.cloudStorage.s3Compatible.region }}
      region: "{{ .Values.cloudStorage.s3Compatible.region }}"
      {{- end }}
      {{- if .Values.cloudStorage.s3Compatible.endpoint }}
      endpoint: "{{ .Values.cloudStorage.s3Compatible.endpoint }}"
      {{- end }}
      {{- if .Values.cloudStorage.s3Compatible.enablePathStyleAddressing }}
      enablePathStyleAddressing: {{ .Values.cloudStorage.s3Compatible.enablePathStyleAddressing }}
      {{- end }}
      {{- if .Values.cloudStorage.s3Compatible.storageClass }}
      storageClass: "{{ .Values.cloudStorage.s3Compatible.storageClass }}"
      {{- end }}
    {{- end }}
    {{- if .Values.cloudStorage.gcs }}
    type: gcs
    gcs:
      bucket: "{{ .Values.cloudStorage.gcs.bucket }}"
      {{- if .Values.cloudStorage.gcs.path }}
      path: "{{ .Values.cloudStorage.gcs.path }}"
      {{- end }}
      gcpCredentials:
        {{- if .Values.cloudStorage.gcs.gcpCredentials.fetchCredentialsFromMetadataService }}
        fetchCredentialsFromMetadataService: {{ .Values.cloudStorage.gcs.gcpCredentials.fetchCredentialsFromMetadataService }}
        {{- else }}
        secretKeySelectors:
          serviceAccountJSON:
            name: "{{ .Values.cloudStorage.gcs.gcpCredentials.secretKeySelectors.serviceAccountJSON.name }}"
            key: "{{ .Values.cloudStorage.gcs.gcpCredentials.secretKeySelectors.serviceAccountJSON.key }}"
        {{- end }}
    {{- end }}
    {{- if .Values.cloudStorage.azureBlob }}
    type: azureBlob
    azureBlob:
      bucket: "{{ .Values.cloudStorage.azureBlob.bucket }}"
      {{- if .Values.cloudStorage.azureBlob.path }}
      path: "{{ .Values.cloudStorage.azureBlob.path }}"
      {{- end }}
      azureCredentials:
        secretKeySelectors:
          storageAccount:
            name: "{{ .Values.cloudStorage.azureBlob.azureCredentials.secretKeySelectors.storageAccount.name }}"
            key: "{{ .Values.cloudStorage.azureBlob.azureCredentials.secretKeySelectors.storageAccount.key }}"
          accessKey:
            name: "{{ .Values.cloudStorage.azureBlob.azureCredentials.secretKeySelectors.accessKey.name }}"
            key: "{{ .Values.cloudStorage.azureBlob.azureCredentials.secretKeySelectors.accessKey.key }}"
    {{- end }}
  {{- end }}
{{ end }}
