{{ if and .Values.configurations.create .Values.configurations.backupconfig.create }}
{{ if and .Values.cloudStorage.s3.enabled .Values.cloudStorage.s3.secretAccessKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: "Helm"
type: Opaque
stringData:
  accessKeyId: {{ .Values.cloudStorage.s3.accessKeyId }}
  secretAccessKey: {{ .Values.cloudStorage.s3.secretAccessKey }}
{{ end }}
{{ end }}