
{{ if and .Values.initScripts.enabled .Values.initScripts.customScripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-custom-scripts
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade,post-install,post-upgrade"
data:
  {{- range .Values.initScripts.customScripts }}
  {{ .name }}.sql: |
    {{ .data }}
  {{ end }}  
{{ end }}
