
{{ if and .Values.initScripts.enabled .Values.initScripts.presets.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sql-scripts
  annotations:
    helm.sh/hook: "pre-install,pre-upgrade,post-install,post-upgrade"
data:
  {{- if .Values.initScripts.presets.harbor.enabled }}
  {{- range .Values.initScripts.presets.harbor.databases }}
  harbor-db-{{ . }}.sql: |
    CREATE DATABASE {{ . | quote }} ;
  {{- end }}
  harbor-init-0.sql: |
    CREATE USER {{ .Values.initScripts.presets.harbor.user }} WITH SUPERUSER PASSWORD '{{ .Values.initScripts.presets.harbor.password }}';
    {{- range .Values.initScripts.presets.harbor.databases }}
    GRANT ALL PRIVILEGES ON DATABASE {{ . | quote }} TO {{ $.Values.initScripts.presets.harbor.user }};
    {{- end }}
  harbor-init-1.sql: |
    CREATE TABLE schema_migrations(version bigint not null primary key, dirty boolean not null);
  {{- end }}
{{ end }}